package com.aivle26.aipm.Entity.project;

public enum WbsSkill {
    DOCUMENT_ANALYSIS,
    REQUIREMENTS_ANALYSIS,
    ARCHITECTURE_DESIGN,
    BACKEND_DEVELOPMENT,
    FRONTEND_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DATA_ENGINEERING,
    SECURITY,
    DATABASE,
    ACCESSIBILITY,
    TESTING,
    DEVOPS
}
