package com.aivle26.aipm.Entity;

public enum WbsSkill {
    DOCUMENT_ANALYSIS,
    REQUIREMENTS_ANALYSIS,
    ARCHITECTURE_DESIGN,
    BACKEND_DEVELOPMENT,
    FRONTEND_DEVELOPMENT,
    TESTING,
    DEVOPS
}
